# Generated by Django 3.0.3 on 2020-02-17 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20200217_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='demande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Articles', to='principal.Demande'),
        ),
    ]
