# Generated by Django 3.0.3 on 2020-02-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20200217_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeur',
            name='key',
            field=models.IntegerField(default=11, unique=True),
            preserve_default=False,
        ),
    ]
