# Generated by Django 3.0.3 on 2020-02-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_demandeur_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeur',
            name='username',
            field=models.CharField(max_length=250, verbose_name="Nom d'utilisateur"),
        ),
    ]
