# Generated by Django 3.0.3 on 2020-02-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20200217_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeur',
            name='key',
        ),
        migrations.AlterField(
            model_name='demandeur',
            name='username',
            field=models.CharField(max_length=250, unique=True, verbose_name="Nom d'utilisateur"),
        ),
    ]
