# Generated by Django 3.0.3 on 2020-02-17 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20200217_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.TextField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
